In [102]:
import os, pandas as pd

In [103]:
os.makedirs(os.path.join('..','data'),exist_ok=True)

In [104]:
data_file = os.path.join('..','data','hosue_tiny.csv')

In [105]:
with open(data_file,'w') as f:
    f.write("Numrooms,alley,price\n")  # 只有NA代表nan,NAN就是字符串 是错的
    f.write('NA,pave,127500\n')
    f.write('2,NA,100\n')
    f.write('3,NA,200\n')
    f.write('NA,NA,NA')

In [131]:
data = pd.read_csv(data_file)

In [107]:
data

   Numrooms alley     price
0       NaN  pave  127500.0
1       2.0   NaN     100.0
2       3.0   NaN     200.0
3       NaN   NaN       NaN

In [132]:
inputs, outputs = data.iloc[:,0:2],data.iloc[:,-1]

In [110]:
outputs

0    127500.0
1       100.0
2       200.0
3         NaN
Name: price, dtype: float64

In [127]:
outputs.dropna()

0    127500.0
1       100.0
2       200.0
Name: price, dtype: float64

In [128]:
outputs

0    127500.0
1       100.0
2       200.0
3         NaN
Name: price, dtype: float64

In [133]:
inputs = inputs.fillna(inputs.mean(numeric_only=True))  # 新版本 或者使用特定列 不过好像没啥用

In [134]:
inputs

   Numrooms alley
0       2.5  pave
1       2.0   NaN
2       3.0   NaN
3       2.5   NaN

In [135]:
inputs['Numrooms'] = inputs['Numrooms'].fillna(inputs['Numrooms'].mean())

In [136]:
inputs

   Numrooms alley
0       2.5  pave
1       2.0   NaN
2       3.0   NaN
3       2.5   NaN

In [137]:
inputs = pd.get_dummies(inputs,dummy_na=True).astype(int)  # 转换成独热编码

In [138]:
inputs

   Numrooms  alley_pave  alley_nan
0         2           1          0
1         2           0          1
2         3           0          1
3         2           0          1

In [139]:
import torch

In [140]:
x = torch.tensor(inputs.to_numpy(dtype=float))

In [141]:
y = torch.tensor(outputs.to_numpy(dtype=float))

In [142]:
x,y

(tensor([[2., 1., 0.],
         [2., 0., 1.],
         [3., 0., 1.],
         [2., 0., 1.]], dtype=torch.float64),
 tensor([1.2750e+05, 1.0000e+02, 2.0000e+02,        nan], dtype=torch.float64))